version: "3.8"

services:
  # Admin
  simpler-admin:
    container_name: simpler-admin
    build:
      context: ./admin
    restart: always
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    networks:
      - simpler_network
    depends_on:
      - simpler-phpmyadmin

    # Webmaster
  simpler-webmaster:
    container_name: simpler-webmaster
    build:
      context: ./webmaster
    restart: always
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
    ports:
      - 3001:3000
    networks:
      - simpler_network
    depends_on:
      - simpler-phpmyadmin

    # Mysql
  simpler-mysql:
    container_name: simpler-mysql
    image: mysql:5.7.36
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: simpler_db
    networks:
      - simpler_network
    volumes:
      - simpler_volume:/usr/src/lib/mysql

    # PhpMyAdmin
  simpler-phpmyadmin:
    container_name: simpler-phpmyadmin
    image: phpmyadmin:5.1.1
    restart: always
    environment:
      PMA_HOST: simpler-mysql
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - 3003:80
    networks:
      - simpler_network
    depends_on:
      - simpler-mysql

networks:
  simpler_network:

volumes:
  simpler_volume:
